language: php

php:
  - 5.4

before_script:
    # System
    - sudo apt-get update -qq

    # Web server
    - sudo apt-get install -y --force-yes php5-curl php5-mysql php5-intl php5-sqlite sqlite3
    - echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    - php -S localhost:8080 -t web/ > /dev/null 2>&1 &

    # XVFB
    - sh -e /etc/init.d/xvfb start
    - export DISPLAY=:99.0

    # Selenium server
    - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.35.0.jar
    #- wget http://chromedriver.storage.googleapis.com/2.4/chromedriver_linux32.zip
    #- unzip chromedriver_linux32.zip
    #- sudo mv chromedriver /usr/bin
    - java -jar selenium-server-standalone-2.35.0.jar > /dev/null 2>&1 &

    # Frontend
    - gem install compass

    # Backend
    - composer self-update
    - composer install --prefer-dist --no-progress --no-interaction
    - ./reset.sh

script:
    - bin/phpspec
    - bin/behat
