# openl10n_editorapi_get_domains:
#     path: /projects/{project}/domains
#     defaults: { _controller: Openl10nEditorBundle:Api/Domain:cget, _format: json }
#     requirements:
#         _method: GET
# openl10n_editorapi_get_domain:
#     path: /projects/{project}/domains/{domain}
#     defaults: { _controller: Openl10nEditorBundle:Api/Domain:get, _format: json }
#     requirements:
#         _method: GET


openl10n_editorapi_get_translations:
    path: /projects/{project}/translations/{target}
    defaults: { _controller: Openl10nEditorBundle:Api/Translation:cget, _format: json }
    requirements:
        _method: GET
openl10n_editorapi_get_translation:
    path: /projects/{project}/translations/{target}/{hash}
    defaults: { _controller: Openl10nEditorBundle:Api/Translation:get, _format: json }
    requirements:
        _method: GET
openl10n_editorapi_put_translation:
    path: /projects/{project}/translations/{target}/{hash}
    defaults: { _controller: Openl10nEditorBundle:Api/Translation:put, _format: json }
    requirements:
        _method: PUT
