openl10n_web:
    resource: "@Openl10nWebBundle/Resources/config/routing.yml"

openl10n_user:
    resource: "@Openl10nUserBundle/Resources/config/routing.yml"

fos_js:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
